######################## default configuration ####################
baseURL = "https://flugebluk.github.io/"
languageCode = "en-us"
title = "Agile Fluency"
theme = "influencer"
summaryLength = "10"
paginate = 6

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "À propos"
  URL = "book"
  weight = 2
  
  [[menu.main]]
  name = "Parties"
  URL = "chapter"
  weight = 3
  
  [[menu.main]]
  name = "Avis"
  URL = "review"
  weight = 4
  
  [[menu.main]]
  name = "L'auteur"
  URL = "author"
  weight = 5
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 6
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 7


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 [beNext](http://www.benextcompany.com) Tous droits réservés"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Navigation get start button
  [params.navButton]
  enable = true

  
############################# Footer ########################
[params.footer]
content = "Petite description du livre rapide à ajouter dans le footer"


############################# post share ###################
[[params.share]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"
